language: python
python:
  - "3.6"

env:
  - CFLAGS="-O0"

# command to install dependencies
install:
  - pip install -r src/requirements/test.txt
  - cd src
  - python manage.py migrate --settings=sgk.settings.test

# command to run tests
script:
  - python manage.py test --settings=sgk.settings.test
