# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20160507_1734'),
        ('coberturas_medicas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antecedente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado_el', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('patologicos', models.TextField(blank=True, verbose_name='patológicos')),
                ('quirurgicos', models.TextField(blank=True, verbose_name='quirúrgicos')),
                ('traumaticos', models.TextField(blank=True, verbose_name='traumáticos')),
                ('alergicos', models.TextField(blank=True, verbose_name='alérgicos')),
                ('heredo_familiar', models.TextField(blank=True, verbose_name='heredo familiar')),
                ('habitos_fisiologicos', models.TextField(blank=True, verbose_name='hábitos fisiológicos')),
                ('habitos_patologicos', models.TextField(blank=True, verbose_name='hábitos patológicos')),
                ('medicaciones', models.TextField(blank=True, verbose_name='medicaciones')),
                ('estudios_complementarios', models.TextField(blank=True, verbose_name='estudios complementarios')),
                ('menarca', models.DateField(null=True, verbose_name='MENARCA')),
                ('fum', models.DateField(null=True, verbose_name='FUM')),
                ('tipo_partos', models.TextField(blank=True, verbose_name='tipo de partos')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
            ],
            options={
                'verbose_name': 'antecedente',
                'verbose_name_plural': 'antecedentes',
            },
        ),
        migrations.CreateModel(
            name='ComentariosHistoriaClinica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado_el', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('comentarios', models.TextField(verbose_name='comentarios')),
            ],
            options={
                'verbose_name': 'comentario de historia clinica',
                'verbose_name_plural': 'comentarios de historia clinica',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado_el', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('fecha_ingreso', models.DateField(verbose_name='fecha de ingreso')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('cobertura_medica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coberturas_medicas.Cobertura', verbose_name='cobertural')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Persona', verbose_name='persona')),
            ],
            options={
                'verbose_name': 'paciente',
                'verbose_name_plural': 'pacientes',
            },
        ),
        migrations.CreateModel(
            name='RegistroBiometrico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado_el', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='peso (kg)')),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='altura (mts)')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_biometricos', to='pacientes.Paciente')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Profesional')),
            ],
            options={
                'verbose_name': 'registro biométrico',
                'verbose_name_plural': 'registros biométricos',
            },
        ),
        migrations.CreateModel(
            name='ImagenesHistoriaClinica',
            fields=[
                ('comentarioshistoriaclinica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pacientes.ComentariosHistoriaClinica')),
                ('imagen', models.ImageField(upload_to='historia_imagenes', verbose_name='imágen')),
            ],
            options={
                'verbose_name': 'imagen de histori clínica',
                'verbose_name_plural': 'imágenes de historia clínica',
            },
            bases=('pacientes.comentarioshistoriaclinica',),
        ),
        migrations.AddField(
            model_name='comentarioshistoriaclinica',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas_historiaclinica', to='pacientes.Paciente'),
        ),
        migrations.AddField(
            model_name='comentarioshistoriaclinica',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Profesional'),
        ),
        migrations.AddField(
            model_name='antecedente',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pacientes.Paciente'),
        ),
    ]
