# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 02:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarioshistoriaclinica',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='comentarioshistoriaclinica',
            name='profesional',
        ),
        migrations.RemoveField(
            model_name='imageneshistoriaclinica',
            name='comentarioshistoriaclinica_ptr',
        ),
        migrations.DeleteModel(
            name='ComentariosHistoriaClinica',
        ),
        migrations.DeleteModel(
            name='ImagenesHistoriaClinica',
        ),
    ]
