# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_auto_20160519_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='antecedente',
            name='actividad_fisica',
            field=models.TextField(blank=True, verbose_name='actividad física'),
        ),
    ]
