# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-03-16 20:58
from __future__ import unicode_literals

import dj_utils.models
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0007_auto_20170129_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageneshistoriaclinica',
            name='imagen',
            field=models.ImageField(upload_to=functools.partial(dj_utils.models.uploadTenantFilename, *('historia_imagenes',), **{}), verbose_name='imágen'),
        ),
    ]
