# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planificacion',
            name='fecha_ingreso',
            field=models.DateField(help_text='Fecha de inicio de tratamiento, normalmente la fecha de la primer sesión.', null=True, verbose_name='fecha de ingreso'),
        ),
    ]
