# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 23:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tratamientos', '0002_auto_20160510_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='comienzo_el',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 15, 23, 28, 35, 95147, tzinfo=utc), verbose_name='fecha y hora de comienzo de sesión'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sesion',
            name='fin_el',
            field=models.DateTimeField(null=True, verbose_name='fecha y hora de fin de sesión'),
        ),
    ]
