# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-01 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamientos', '0003_auto_20160515_2028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objetivo',
            options={'ordering': ('fecha_inicio',), 'verbose_name': 'objectivo', 'verbose_name_plural': 'objetivos'},
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='fecha_inicio',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='fecha de inicio'),
        ),
    ]
