# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-01 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tratamientos', '0005_sesion_profesional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='core.Profesional'),
        ),
    ]
