# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-28 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamientos', '0007_planificacion_motivo_finalizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='planificacion',
            name='por_sesion',
            field=models.BooleanField(default=False, help_text='Seleccione esta opción si el tratamiento no depende de una cantidad determinada de sesiones.', verbose_name='por sesión'),
        ),
        migrations.AlterField(
            model_name='planificacion',
            name='cantidad_sesiones',
            field=models.IntegerField(blank=True, help_text='Cantidad de sesiones necesarias recetadas por el médico.', null=True, verbose_name='cantidad de sesiones'),
        ),
    ]
