# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-11 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tratamientos', '0008_auto_20170328_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='planificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='tratamientos.Planificacion'),
        ),
    ]
