# Generated by Django 2.2.1 on 2019-05-23 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tratamientos', '0011_remove_sesion_motivo_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='planificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones', to='tratamientos.Planificacion'),
        ),
    ]
