# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-01-30 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultorio',
            name='pagado_hasta',
            field=models.DateField(null=True),
        ),
    ]
