# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('core', '0002_auto_20160507_1734'),
        ('coberturas_medicas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado_el', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('dia', models.DateField(verbose_name='día')),
                ('hora', models.TimeField(verbose_name='hora')),
                ('duracion', models.PositiveSmallIntegerField(default=60, help_text='duración en minutos de la sesión.', verbose_name='duración')),
                ('motivo', models.CharField(blank=True, max_length=255, verbose_name='motivo')),
                ('no_asistio', models.BooleanField(default=False, verbose_name='¿asistió?')),
                ('no_aviso', models.BooleanField(default=False, verbose_name='¿avisó?')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('nombre_paciente', models.CharField(blank=True, help_text='Dejar en blanco si el paciente se encuentra en el sistema.', max_length=255, verbose_name='nombre del paciente')),
                ('cobertura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coberturas_medicas.Cobertura', verbose_name='cobertura')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pacientes.Paciente', verbose_name='paciente')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Profesional', verbose_name='profesional')),
            ],
            options={
                'verbose_name': 'turno',
                'verbose_name_plural': 'turnos',
            },
        ),
    ]
