# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tratamientos', '0003_auto_20160515_2028'),
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='sesion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tratamientos.Sesion', verbose_name='sesión realizada'),
        ),
    ]
