# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 04:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_auto_20160515_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='sesion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turno_dado', to='tratamientos.Sesion', verbose_name='sesión realizada'),
        ),
    ]
