# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-17 00:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0004_auto_20160519_0134'),
    ]

    operations = [
        migrations.RenameField('Turno', 'asistio', 'no_asistio'),
        migrations.RenameField('Turno', 'aviso', 'no_aviso')
    ]
