# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-16 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0004_auto_20160519_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='asistio',
            field=models.BooleanField(default=False, help_text='Marcar en caso de NO asistencia del paciente.', verbose_name='No asistió'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='aviso',
            field=models.BooleanField(default=False, help_text='Marcar en caso de NO asistencia sin previo no_aviso.', verbose_name='No avisó'),
        ),
    ]
