# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-17 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0005_auto_20160816_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='no_asistio',
            field=models.BooleanField(default=False, help_text='Marcar en caso de NO asistencia del paciente.', verbose_name='No asistió'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='no_aviso',
            field=models.BooleanField(default=False, help_text='Marcar en caso de NO asistencia sin previo no_aviso.', verbose_name='No avisó'),
        ),
    ]
