# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 20:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado_el', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('nombre', models.CharField(blank=True, max_length=255, verbose_name='nombre')),
                ('apellido', models.CharField(blank=True, max_length=255, verbose_name='npellido')),
                ('telefono', models.CharField(blank=True, max_length=255, verbose_name='teléfono')),
                ('celular', models.CharField(blank=True, max_length=255, verbose_name='celular')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('horario', models.CharField(blank=True, max_length=255, verbose_name='horario de contacto')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
            ],
            options={
                'verbose_name': 'contacto',
                'verbose_name_plural': 'contactos',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado_el', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=255, verbose_name='apellido')),
                ('fecha_nacimiento', models.DateField(verbose_name='fecha de nacimiento')),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otro')], default='F', max_length=1, verbose_name='género')),
                ('estado_civil', models.CharField(choices=[('S', 'Soltero'), ('C', 'Casado'), ('D', 'Divorciado'), ('V', 'Viudo'), ('CV', 'Concuvinato')], default='S', max_length=3, verbose_name='estado civíl')),
                ('dni', models.IntegerField(unique=True, verbose_name='DNI')),
                ('domicilio', models.CharField(blank=True, max_length=255, verbose_name='domicilio')),
                ('imagen_perfil', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='imagen_perfil')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('info_contacto', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Contacto', verbose_name='contacto')),
            ],
            options={
                'verbose_name': 'persona',
                'verbose_name_plural': 'personas',
            },
        ),
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado_el', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='nombre de la profesión')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
            ],
            options={
                'verbose_name': 'profesión',
                'verbose_name_plural': 'profesiones',
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado_el', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Persona', verbose_name='persona')),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'profesional',
                'verbose_name_plural': 'profesionales',
            },
        ),
        migrations.AddField(
            model_name='persona',
            name='profesion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Profesion', verbose_name='profesión'),
        ),
    ]
