# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160507_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='dni',
            field=models.IntegerField(blank=True, null=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(null=True, verbose_name='fecha de nacimiento'),
        ),
    ]
