# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-01 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160508_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='profesion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='profesión'),
        ),
    ]
