# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-01 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160901_0830'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profesion',
        ),
    ]
