# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-27 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contacto_notificar_sms'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='titulo',
            field=models.CharField(blank=True, help_text='Ej: Lic.', max_length=64, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='celular',
            field=models.CharField(blank=True, help_text='Sin guiones ni espacios.', max_length=255, verbose_name='celular'),
        ),
    ]
