# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-03-16 20:58
from __future__ import unicode_literals

import dj_utils.models
from django.db import migrations
import easy_thumbnails.fields
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170129_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='imagen_perfil',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=functools.partial(dj_utils.models.uploadTenantFilename, *('imagen_perfil',), **{})),
        ),
    ]
