# Generated by Django 2.2.1 on 2019-05-23 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180316_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='info_contacto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Contacto', verbose_name='contacto'),
        ),
    ]
