# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coberturas_medicas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobertura',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='registrovalorprestacion',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, help_text='Si la fecha está vacia, el valor es el vigente. Será establecido automáticamente al ingresar un nuevo valor', null=True, verbose_name='fecha de baja'),
        ),
    ]
