# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 00:39
from __future__ import unicode_literals

from django.db import migrations

def add_coberturas_privada(apps, scheme_editor):
    Cobertura = apps.get_model('coberturas_medicas', 'Cobertura')
    RegistroValorPrestacion = apps.get_model('coberturas_medicas', 'RegistroValorPrestacion')
    cobertura = Cobertura(nombre="Particular", paga_por_sesion=True)
    cobertura.save()
    valor = RegistroValorPrestacion(cobertura=cobertura, monto=150)
    valor.save()

class Migration(migrations.Migration):

    dependencies = [
        ('coberturas_medicas', '0002_auto_20160525_2134'),
    ]

    operations = [
        migrations.RunPython(add_coberturas_privada)
    ]
