# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-29 18:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coberturas_medicas', '0004_cobertura_cobertura_propia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cobertura',
            options={'ordering': ('nombre',), 'verbose_name': 'cobertura médica', 'verbose_name_plural': 'coberturas médicas'},
        ),
    ]
